app:
  gin:
    port: 18080
  grpc:
    port: 18081
storage:
  redis: redis://default:ayou1209@10.0.0.30:30356/7
  mysql: dwgoing:ayou1209@tcp(10.0.0.30:30743)/FUNDS_SYSTEM_7?charset=utf8mb4&parseTime=True&loc=Local
chain:
  nodes:
    - https://matic.getblock.io/734e51ea-b0bc-43f5-aa34-0969d8a2c6b1/testnet/
    - https://rpc.ankr.com/polygon_mumbai
    - https://endpoints.omniatech.io/v1/matic/mumbai/public
    - https://polygon-mumbai.blockpi.network/v1/rpc/public
