host:
  gin:
    port: 18080
  grpc:
    port: 18081
storage:
  redis: redis://default:ayou1209@10.0.0.30:30356/7
  mysql: dwgoing:ayou1209@tcp(10.0.0.30:30743)/FUNDS_SYSTEM_7?charset=utf8mb4&parseTime=True&loc=Local
funds:
  nodes:
    - https://matic.getblock.io/734e51ea-b0bc-43f5-aa34-0969d8a2c6b1/testnet/
    - https://rpc.ankr.com/polygon_mumbai
    - https://endpoints.omniatech.io/v1/matic/mumbai/public
    - https://polygon-mumbai.blockpi.network/v1/rpc/public
  mnemonic: increase squeeze thank version toast soap deposit dove garbage margin metal repair
  walletMaxNumber: 10
  expireTime: 1800 # 30 min
  expireDelay: 900 # 15 min
  collectThresholds:
    0x466DD1e48570FAA2E7f69B75139813e4F8EF75c2: 5
