//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package module

import (
	"crypto/ecdsa"
	"github.com/DwGoing/MarketBrain/internal/funds_service/model"
	"github.com/DwGoing/MarketBrain/pkg/enum"
	"github.com/DwGoing/MarketBrain/pkg/hd_wallet"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/fbsobreira/gotron-sdk/pkg/client"
	"github.com/fbsobreira/gotron-sdk/pkg/proto/core"
	v9 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	timex "time"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &chain_{}
		},
	})
	chainStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Chain{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(chainStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &config_{}
		},
	})
	configStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Config{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(configStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &eventBus_{}
		},
	})
	eventBusStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &EventBus{}
		},
		ConstructFunc: func(i interface{}, _ interface{}) (interface{}, error) {
			impl := i.(*EventBus)
			var constructFunc EventBusConstructFunc = NewEventBus
			return constructFunc(impl)
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(eventBusStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &notify_{}
		},
	})
	notifyStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Notify{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(notifyStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &storage_{}
		},
	})
	storageStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Storage{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(storageStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &treasury_{}
		},
	})
	treasuryStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Treasury{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(treasuryStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &tron_{}
		},
	})
	tronStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Tron{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(tronStructDescriptor)
}

type EventBusConstructFunc func(impl *EventBus) (*EventBus, error)
type chain_ struct {
	GetAccount_               func(currencyType hd_wallet.Currency, index int64) (*hd_wallet.Account, error)
	GetCurrentHeight_         func(chainType enum.ChainType) (int64, error)
	GetBalance_               func(chainType enum.ChainType, contract *string, wallet string) (float64, error)
	Transfer_                 func(chainType enum.ChainType, token *string, from *hd_wallet.Account, to string, amount float64, remarks string) (string, error)
	GetBlock_                 func(chainType enum.ChainType, height int64) (*model.Block, error)
	GetTransactionFromBlocks_ func(chainType enum.ChainType, start int64, end int64) ([]model.Transaction, error)
	DecodeTransaction_        func(chainType enum.ChainType, txHash string) (*model.Transaction, int64, error)
	GetTransactionsByAddress_ func(chainType enum.ChainType, address string, token *string, endTime timex.Time) ([]model.Transaction, error)
}

func (c *chain_) GetAccount(currencyType hd_wallet.Currency, index int64) (*hd_wallet.Account, error) {
	return c.GetAccount_(currencyType, index)
}

func (c *chain_) GetCurrentHeight(chainType enum.ChainType) (int64, error) {
	return c.GetCurrentHeight_(chainType)
}

func (c *chain_) GetBalance(chainType enum.ChainType, contract *string, wallet string) (float64, error) {
	return c.GetBalance_(chainType, contract, wallet)
}

func (c *chain_) Transfer(chainType enum.ChainType, token *string, from *hd_wallet.Account, to string, amount float64, remarks string) (string, error) {
	return c.Transfer_(chainType, token, from, to, amount, remarks)
}

func (c *chain_) GetBlock(chainType enum.ChainType, height int64) (*model.Block, error) {
	return c.GetBlock_(chainType, height)
}

func (c *chain_) GetTransactionFromBlocks(chainType enum.ChainType, start int64, end int64) ([]model.Transaction, error) {
	return c.GetTransactionFromBlocks_(chainType, start, end)
}

func (c *chain_) DecodeTransaction(chainType enum.ChainType, txHash string) (*model.Transaction, int64, error) {
	return c.DecodeTransaction_(chainType, txHash)
}

func (c *chain_) GetTransactionsByAddress(chainType enum.ChainType, address string, token *string, endTime timex.Time) ([]model.Transaction, error) {
	return c.GetTransactionsByAddress_(chainType, address, token, endTime)
}

type config_ struct {
	Set_  func(configs map[string]any) error
	Load_ func() (*model.Configs, error)
}

func (c *config_) Set(configs map[string]any) error {
	return c.Set_(configs)
}

func (c *config_) Load() (*model.Configs, error) {
	return c.Load_()
}

type eventBus_ struct {
}

type notify_ struct {
	Send_ func(url string, data []byte) error
}

func (n *notify_) Send(url string, data []byte) error {
	return n.Send_(url, data)
}

type storage_ struct {
	GetRedisClient_ func() (*v9.Client, error)
	GetMysqlClient_ func() (*gorm.DB, error)
}

func (s *storage_) GetRedisClient() (*v9.Client, error) {
	return s.GetRedisClient_()
}

func (s *storage_) GetMysqlClient() (*gorm.DB, error) {
	return s.GetMysqlClient_()
}

type treasury_ struct {
	CreateRechargeOrder_            func(externalIdentity string, externalData []byte, callbackUrl string, chainType string, amount float64, walletIndex int64) (string, string, timex.Time, error)
	SubmitRechargeOrderTransaction_ func(orderId string, txHash string) error
	CancelRechargeOrder_            func(orderId string) error
	CheckRechargeOrderStatus_       func(id string) (enum.RechargeStatus, error)
	CheckRechargeOrdersStatus_      func() ([]model.WalletCollectionInfomation, error)
	GetRechargeOrders_              func(conditions string, conditionsParameters []any, pageSize int64, pageIndex int64) ([]model.RechargeOrderRecord, error)
}

func (t *treasury_) CreateRechargeOrder(externalIdentity string, externalData []byte, callbackUrl string, chainType string, amount float64, walletIndex int64) (string, string, timex.Time, error) {
	return t.CreateRechargeOrder_(externalIdentity, externalData, callbackUrl, chainType, amount, walletIndex)
}

func (t *treasury_) SubmitRechargeOrderTransaction(orderId string, txHash string) error {
	return t.SubmitRechargeOrderTransaction_(orderId, txHash)
}

func (t *treasury_) CancelRechargeOrder(orderId string) error {
	return t.CancelRechargeOrder_(orderId)
}

func (t *treasury_) CheckRechargeOrderStatus(id string) (enum.RechargeStatus, error) {
	return t.CheckRechargeOrderStatus_(id)
}

func (t *treasury_) CheckRechargeOrdersStatus() ([]model.WalletCollectionInfomation, error) {
	return t.CheckRechargeOrdersStatus_()
}

func (t *treasury_) GetRechargeOrders(conditions string, conditionsParameters []any, pageSize int64, pageIndex int64) ([]model.RechargeOrderRecord, error) {
	return t.GetRechargeOrders_(conditions, conditionsParameters, pageSize, pageIndex)
}

type tron_ struct {
	GetTronClient_                 func(nodes []string, apiKey string) (*client.GrpcClient, error)
	SendTronTransaction_           func(client *client.GrpcClient, privateKey *ecdsa.PrivateKey, tx *core.Transaction, waitReceipt bool) (*core.TransactionInfo, error)
	DecodeTronTransaction_         func(client *client.GrpcClient, txHash string) (*model.Transaction, error)
	GetTronTransactionsFromBlocks_ func(client *client.GrpcClient, start int64, end int64) ([]model.Transaction, error)
	GetTronTransactionsByAddress_  func(address string, token *string, endTime timex.Time) ([]model.Transaction, error)
}

func (t *tron_) GetTronClient(nodes []string, apiKey string) (*client.GrpcClient, error) {
	return t.GetTronClient_(nodes, apiKey)
}

func (t *tron_) SendTronTransaction(client *client.GrpcClient, privateKey *ecdsa.PrivateKey, tx *core.Transaction, waitReceipt bool) (*core.TransactionInfo, error) {
	return t.SendTronTransaction_(client, privateKey, tx, waitReceipt)
}

func (t *tron_) DecodeTronTransaction(client *client.GrpcClient, txHash string) (*model.Transaction, error) {
	return t.DecodeTronTransaction_(client, txHash)
}

func (t *tron_) GetTronTransactionsFromBlocks(client *client.GrpcClient, start int64, end int64) ([]model.Transaction, error) {
	return t.GetTronTransactionsFromBlocks_(client, start, end)
}

func (t *tron_) GetTronTransactionsByAddress(address string, token *string, endTime timex.Time) ([]model.Transaction, error) {
	return t.GetTronTransactionsByAddress_(address, token, endTime)
}

type ChainIOCInterface interface {
	GetAccount(currencyType hd_wallet.Currency, index int64) (*hd_wallet.Account, error)
	GetCurrentHeight(chainType enum.ChainType) (int64, error)
	GetBalance(chainType enum.ChainType, contract *string, wallet string) (float64, error)
	Transfer(chainType enum.ChainType, token *string, from *hd_wallet.Account, to string, amount float64, remarks string) (string, error)
	GetBlock(chainType enum.ChainType, height int64) (*model.Block, error)
	GetTransactionFromBlocks(chainType enum.ChainType, start int64, end int64) ([]model.Transaction, error)
	DecodeTransaction(chainType enum.ChainType, txHash string) (*model.Transaction, int64, error)
	GetTransactionsByAddress(chainType enum.ChainType, address string, token *string, endTime timex.Time) ([]model.Transaction, error)
}

type ConfigIOCInterface interface {
	Set(configs map[string]any) error
	Load() (*model.Configs, error)
}

type EventBusIOCInterface interface {
}

type NotifyIOCInterface interface {
	Send(url string, data []byte) error
}

type StorageIOCInterface interface {
	GetRedisClient() (*v9.Client, error)
	GetMysqlClient() (*gorm.DB, error)
}

type TreasuryIOCInterface interface {
	CreateRechargeOrder(externalIdentity string, externalData []byte, callbackUrl string, chainType string, amount float64, walletIndex int64) (string, string, timex.Time, error)
	SubmitRechargeOrderTransaction(orderId string, txHash string) error
	CancelRechargeOrder(orderId string) error
	CheckRechargeOrderStatus(id string) (enum.RechargeStatus, error)
	CheckRechargeOrdersStatus() ([]model.WalletCollectionInfomation, error)
	GetRechargeOrders(conditions string, conditionsParameters []any, pageSize int64, pageIndex int64) ([]model.RechargeOrderRecord, error)
}

type TronIOCInterface interface {
	GetTronClient(nodes []string, apiKey string) (*client.GrpcClient, error)
	SendTronTransaction(client *client.GrpcClient, privateKey *ecdsa.PrivateKey, tx *core.Transaction, waitReceipt bool) (*core.TransactionInfo, error)
	DecodeTronTransaction(client *client.GrpcClient, txHash string) (*model.Transaction, error)
	GetTronTransactionsFromBlocks(client *client.GrpcClient, start int64, end int64) ([]model.Transaction, error)
	GetTronTransactionsByAddress(address string, token *string, endTime timex.Time) ([]model.Transaction, error)
}

var _chainSDID string

func GetChain() (*Chain, error) {
	if _chainSDID == "" {
		_chainSDID = util.GetSDIDByStructPtr(new(Chain))
	}
	i, err := normal.GetImpl(_chainSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Chain)
	return impl, nil
}

func GetChainIOCInterface() (ChainIOCInterface, error) {
	if _chainSDID == "" {
		_chainSDID = util.GetSDIDByStructPtr(new(Chain))
	}
	i, err := normal.GetImplWithProxy(_chainSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ChainIOCInterface)
	return impl, nil
}

var _configSDID string

func GetConfig() (*Config, error) {
	if _configSDID == "" {
		_configSDID = util.GetSDIDByStructPtr(new(Config))
	}
	i, err := normal.GetImpl(_configSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Config)
	return impl, nil
}

func GetConfigIOCInterface() (ConfigIOCInterface, error) {
	if _configSDID == "" {
		_configSDID = util.GetSDIDByStructPtr(new(Config))
	}
	i, err := normal.GetImplWithProxy(_configSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ConfigIOCInterface)
	return impl, nil
}

var _eventBusSDID string

func GetEventBusSingleton() (*EventBus, error) {
	if _eventBusSDID == "" {
		_eventBusSDID = util.GetSDIDByStructPtr(new(EventBus))
	}
	i, err := singleton.GetImpl(_eventBusSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*EventBus)
	return impl, nil
}

func GetEventBusIOCInterfaceSingleton() (EventBusIOCInterface, error) {
	if _eventBusSDID == "" {
		_eventBusSDID = util.GetSDIDByStructPtr(new(EventBus))
	}
	i, err := singleton.GetImplWithProxy(_eventBusSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(EventBusIOCInterface)
	return impl, nil
}

type ThisEventBus struct {
}

func (t *ThisEventBus) This() EventBusIOCInterface {
	thisPtr, _ := GetEventBusIOCInterfaceSingleton()
	return thisPtr
}

var _notifySDID string

func GetNotify() (*Notify, error) {
	if _notifySDID == "" {
		_notifySDID = util.GetSDIDByStructPtr(new(Notify))
	}
	i, err := normal.GetImpl(_notifySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Notify)
	return impl, nil
}

func GetNotifyIOCInterface() (NotifyIOCInterface, error) {
	if _notifySDID == "" {
		_notifySDID = util.GetSDIDByStructPtr(new(Notify))
	}
	i, err := normal.GetImplWithProxy(_notifySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(NotifyIOCInterface)
	return impl, nil
}

var _storageSDID string

func GetStorage() (*Storage, error) {
	if _storageSDID == "" {
		_storageSDID = util.GetSDIDByStructPtr(new(Storage))
	}
	i, err := normal.GetImpl(_storageSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Storage)
	return impl, nil
}

func GetStorageIOCInterface() (StorageIOCInterface, error) {
	if _storageSDID == "" {
		_storageSDID = util.GetSDIDByStructPtr(new(Storage))
	}
	i, err := normal.GetImplWithProxy(_storageSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(StorageIOCInterface)
	return impl, nil
}

var _treasurySDID string

func GetTreasury() (*Treasury, error) {
	if _treasurySDID == "" {
		_treasurySDID = util.GetSDIDByStructPtr(new(Treasury))
	}
	i, err := normal.GetImpl(_treasurySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Treasury)
	return impl, nil
}

func GetTreasuryIOCInterface() (TreasuryIOCInterface, error) {
	if _treasurySDID == "" {
		_treasurySDID = util.GetSDIDByStructPtr(new(Treasury))
	}
	i, err := normal.GetImplWithProxy(_treasurySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(TreasuryIOCInterface)
	return impl, nil
}

var _tronSDID string

func GetTron() (*Tron, error) {
	if _tronSDID == "" {
		_tronSDID = util.GetSDIDByStructPtr(new(Tron))
	}
	i, err := normal.GetImpl(_tronSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Tron)
	return impl, nil
}

func GetTronIOCInterface() (TronIOCInterface, error) {
	if _tronSDID == "" {
		_tronSDID = util.GetSDIDByStructPtr(new(Tron))
	}
	i, err := normal.GetImplWithProxy(_tronSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(TronIOCInterface)
	return impl, nil
}
