//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package module

import (
	contextx "context"
	"github.com/DwGoing/MarketBrain/internal/funds_service/module/config_generated"
	"github.com/DwGoing/MarketBrain/internal/funds_service/module/treasury_generated"
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
	"github.com/gin-gonic/gin"
	v9 "github.com/redis/go-redis/v9"
	"google.golang.org/protobuf/types/known/emptypb"
	"gorm.io/gorm"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &chain_{}
		},
	})
	chainStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Chain{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(chainStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &config_{}
		},
	})
	configStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Config{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(configStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &eventBus_{}
		},
	})
	eventBusStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &EventBus{}
		},
		ConstructFunc: func(i interface{}, _ interface{}) (interface{}, error) {
			impl := i.(*EventBus)
			var constructFunc EventBusConstructFunc = NewEventBus
			return constructFunc(impl)
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(eventBusStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &storage_{}
		},
	})
	storageStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Storage{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(storageStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &treasury_{}
		},
	})
	treasuryStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &Treasury{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	normal.RegisterStructDescriptor(treasuryStructDescriptor)
}

type EventBusConstructFunc func(impl *EventBus) (*EventBus, error)
type chain_ struct {
}

type config_ struct {
	Set_     func(ctx contextx.Context, request *config_generated.SetRequest) (*emptypb.Empty, error)
	SetApi_  func(ctx *gin.Context)
	Load_    func(ctx contextx.Context, request *emptypb.Empty) (*config_generated.LoadResponse, error)
	LoadApi_ func(ctx *gin.Context)
}

func (c *config_) Set(ctx contextx.Context, request *config_generated.SetRequest) (*emptypb.Empty, error) {
	return c.Set_(ctx, request)
}

func (c *config_) SetApi(ctx *gin.Context) {
	c.SetApi_(ctx)
}

func (c *config_) Load(ctx contextx.Context, request *emptypb.Empty) (*config_generated.LoadResponse, error) {
	return c.Load_(ctx, request)
}

func (c *config_) LoadApi(ctx *gin.Context) {
	c.LoadApi_(ctx)
}

type eventBus_ struct {
}

type storage_ struct {
	GetRedisClient_ func() (*v9.Client, error)
	GetMysqlClient_ func() (*gorm.DB, error)
}

func (s *storage_) GetRedisClient() (*v9.Client, error) {
	return s.GetRedisClient_()
}

func (s *storage_) GetMysqlClient() (*gorm.DB, error) {
	return s.GetMysqlClient_()
}

type treasury_ struct {
	CreateRechargeOrder_    func(ctx contextx.Context, request *treasury_generated.CreateRechargeOrderRequest) (*treasury_generated.CreateRechargeOrderResponse, error)
	CreateRechargeOrderApi_ func(ctx *gin.Context)
}

func (t *treasury_) CreateRechargeOrder(ctx contextx.Context, request *treasury_generated.CreateRechargeOrderRequest) (*treasury_generated.CreateRechargeOrderResponse, error) {
	return t.CreateRechargeOrder_(ctx, request)
}

func (t *treasury_) CreateRechargeOrderApi(ctx *gin.Context) {
	t.CreateRechargeOrderApi_(ctx)
}

type ChainIOCInterface interface {
}

type ConfigIOCInterface interface {
	Set(ctx contextx.Context, request *config_generated.SetRequest) (*emptypb.Empty, error)
	SetApi(ctx *gin.Context)
	Load(ctx contextx.Context, request *emptypb.Empty) (*config_generated.LoadResponse, error)
	LoadApi(ctx *gin.Context)
}

type EventBusIOCInterface interface {
}

type StorageIOCInterface interface {
	GetRedisClient() (*v9.Client, error)
	GetMysqlClient() (*gorm.DB, error)
}

type TreasuryIOCInterface interface {
	CreateRechargeOrder(ctx contextx.Context, request *treasury_generated.CreateRechargeOrderRequest) (*treasury_generated.CreateRechargeOrderResponse, error)
	CreateRechargeOrderApi(ctx *gin.Context)
}

var _chainSDID string

func GetChain() (*Chain, error) {
	if _chainSDID == "" {
		_chainSDID = util.GetSDIDByStructPtr(new(Chain))
	}
	i, err := normal.GetImpl(_chainSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Chain)
	return impl, nil
}

func GetChainIOCInterface() (ChainIOCInterface, error) {
	if _chainSDID == "" {
		_chainSDID = util.GetSDIDByStructPtr(new(Chain))
	}
	i, err := normal.GetImplWithProxy(_chainSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ChainIOCInterface)
	return impl, nil
}

var _configSDID string

func GetConfig() (*Config, error) {
	if _configSDID == "" {
		_configSDID = util.GetSDIDByStructPtr(new(Config))
	}
	i, err := normal.GetImpl(_configSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Config)
	return impl, nil
}

func GetConfigIOCInterface() (ConfigIOCInterface, error) {
	if _configSDID == "" {
		_configSDID = util.GetSDIDByStructPtr(new(Config))
	}
	i, err := normal.GetImplWithProxy(_configSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(ConfigIOCInterface)
	return impl, nil
}

var _eventBusSDID string

func GetEventBusSingleton() (*EventBus, error) {
	if _eventBusSDID == "" {
		_eventBusSDID = util.GetSDIDByStructPtr(new(EventBus))
	}
	i, err := singleton.GetImpl(_eventBusSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*EventBus)
	return impl, nil
}

func GetEventBusIOCInterfaceSingleton() (EventBusIOCInterface, error) {
	if _eventBusSDID == "" {
		_eventBusSDID = util.GetSDIDByStructPtr(new(EventBus))
	}
	i, err := singleton.GetImplWithProxy(_eventBusSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(EventBusIOCInterface)
	return impl, nil
}

type ThisEventBus struct {
}

func (t *ThisEventBus) This() EventBusIOCInterface {
	thisPtr, _ := GetEventBusIOCInterfaceSingleton()
	return thisPtr
}

var _storageSDID string

func GetStorage() (*Storage, error) {
	if _storageSDID == "" {
		_storageSDID = util.GetSDIDByStructPtr(new(Storage))
	}
	i, err := normal.GetImpl(_storageSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Storage)
	return impl, nil
}

func GetStorageIOCInterface() (StorageIOCInterface, error) {
	if _storageSDID == "" {
		_storageSDID = util.GetSDIDByStructPtr(new(Storage))
	}
	i, err := normal.GetImplWithProxy(_storageSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(StorageIOCInterface)
	return impl, nil
}

var _treasurySDID string

func GetTreasury() (*Treasury, error) {
	if _treasurySDID == "" {
		_treasurySDID = util.GetSDIDByStructPtr(new(Treasury))
	}
	i, err := normal.GetImpl(_treasurySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*Treasury)
	return impl, nil
}

func GetTreasuryIOCInterface() (TreasuryIOCInterface, error) {
	if _treasurySDID == "" {
		_treasurySDID = util.GetSDIDByStructPtr(new(Treasury))
	}
	i, err := normal.GetImplWithProxy(_treasurySDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(TreasuryIOCInterface)
	return impl, nil
}
