app:
  gin:
    port: 18080
  grpc:
    port: 18081
storage:
  redis: redis://default:ayou1209@10.0.0.30:30356/1
  mysql: dwgoing:ayou1209@tcp(10.0.0.30:30743)/FUNDS_SERVICE?charset=utf8mb4&parseTime=True&loc=Local
chain:
  nodes:
    - https://rpc.ankr.com/polygon_mumbai
    - https://polygon-mumbai.blockpi.network/v1/rpc/public
    - https://matic.getblock.io/734e51ea-b0bc-43f5-aa34-0969d8a2c6b1/testnet/
    - https://endpoints.omniatech.io/v1/matic/mumbai/public
    - https://polygon-mumbai.gateway.tenderly.co
    - https://polygon-mumbai.g.alchemy.com/v2/demo
    - https://gateway.tenderly.co/public/polygon-mumbai
    - https://api.zan.top/node/v1/polygon/mumbai/public
