definitions:
  controller.GetBalanceResponse:
    properties:
      balance:
        type: string
      code:
        type: integer
      message:
        type: string
    type: object
  controller.GetRechargeWalletRequest:
    properties:
      amount:
        type: string
      callbackUrl:
        type: string
      externalData:
        items:
          type: integer
        type: array
      externalIdentity:
        type: string
      token:
        type: string
    type: object
  controller.GetRechargeWalletResponse:
    properties:
      address:
        type: string
      code:
        type: integer
      expireAt:
        type: integer
      id:
        type: string
      message:
        type: string
    type: object
  controller.LoadResponse:
    properties:
      code:
        type: integer
      collectThresholds:
        additionalProperties:
          type: number
        type: object
      expireDelay:
        type: integer
      expireTime:
        type: integer
      message:
        type: string
      mnemonic:
        type: string
      walletMaxNumber:
        type: integer
    type: object
  controller.SetRequest:
    properties:
      collectThresholds:
        additionalProperties:
          type: number
        type: object
      expireDelay:
        type: integer
      expireTime:
        type: integer
      mnemonic:
        type: string
      walletMaxNumber:
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/chain/getBalance:
    get:
      parameters:
      - description: 查询地址
        in: query
        name: address
        required: true
        type: string
      - description: 查询Token
        in: query
        name: token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetBalanceResponse'
      summary: 查询余额
  /v1/config/load:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.LoadResponse'
      summary: 加载配置
  /v1/config/set:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.SetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 修改配置
  /v1/funds/getRechargeRecords:
    get:
      parameters:
      - description: 充值记录Id
        in: query
        name: id
        type: string
      - description: 外部标识
        in: query
        name: externalIdentity
        type: string
      - description: 充值Token
        in: query
        name: token
        type: string
      - description: 创建开始时间戳
        in: query
        name: createdStart
        type: integer
      - description: 创建结束时间戳
        in: query
        name: createdEnd
        type: integer
      - description: 页面大小
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageIndex
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetRechargeWalletResponse'
      summary: 获取充值记录
  /v1/funds/getRechargeWallet:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.GetRechargeWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetRechargeWalletResponse'
      summary: 获取充值钱包
swagger: "2.0"
